#! /bin/bash
found=false

while [ $found = "false" ]; do
	if command -v xcode-select &> /dev/null; then
		found=true
		echo "Xcode installed, installing commandline tools if not already installed"
		xcode-select --install 2> /dev/null
	else
		printf "Xcode is not installed, would you like to install it now? (y/n): "
		read installXCode
		if [ $installXCode = "y"] || [ $installXCode = "yes" ]; then
			echo "Opening up the browser to the app stores Xcode page"
			open https://itunes.apple.com/us/app/xcode/id497799835?mt=12
		else
			echo " Xcode is needed for anything else to install. Shutting down."
			exit
		fi
	fi
done
